version: '2.1'

services:
  coredns:
    image: coredns/coredns:1.10.1
    restart: always
    command: -conf /root/coredns/config/Corefile
    ports:
      - 192.168.1.194:53:53/udp
    volumes:
      - ./config:/root/coredns/config/

