version: '3'

services:
  coredns:
    image: coredns/coredns:1.10.1
    restart: always
    command: -conf /root/coredns/config/Corefile
    ports:
      - 192.168.1.194:53:53/udp
    volumes:
      - ./config:/root/coredns/config/
  nginx:
    image: nginx:1.23.3
    ports:
      - 192.168.1.194:80:80
    volumes:
      - ./nginx-config:/etc/nginx/conf.d
  pihole:
    image: pihole/pihole:latest
    ports:
      - "192.168.1.194:38053:53/tcp"
      - "192.168.1.194:38053:53/udp"
      - "192.168.1.194:38080:80/tcp"
    environment:
      TZ: 'Asia/Seoul'
      WEBPASSWORD: '1234' # 'set a secure password here or it will be random'
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped
  vpn:
    image: cloudflare/cloudflared:latest
    network_mode: host
    command: proxy-dns --address 192.168.1.194 --port 15053
