version: "3"
services:
  calibre:
    image: lscr.io/linuxserver/calibre:6.12.0
    container_name: calibre
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Seoul
      #- FILE__PASSWORD=/home/jo/apps/calibre/secrets/password
    volumes:
      - ./config:/config
    ports:
      - 192.168.1.194:8080:8080 # desktop gui
      - 192.168.1.194:8081:8081 # webserver gui
      - 192.168.1.194:9090:9090 # wireless
    restart: unless-stopped
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:amd64-version-0.6.19
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Seoul
      - DOCKER_MODS=linuxserver/mods:universal-calibre #optional
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
      - ./config:/config
      - "./config/Calibre Library:/books"
    ports:
      - 192.168.1.194:8083:8083
    restart: unless-stopped
